### PR TITLE
Drupal upgrade styling fixes

### LINKED ISSUE #48: Update index.html with new css links from drupal upgrade
Update index.html with new script links from drupal upgrade

### PR DESCRIPTION
**Pull request by j-tafoya**
Wholesale changes to adjust to the new EPA CSS relying on flex, grid, and USWDS components
You can see the test version in cloud.gov [here](https://test-power-profiler-drupal-upgrade.app.cloud.gov)
- Added new HTML template from production site for local development
- Fixed issues resulting in changes to new EPA CSS
- Fixed whitespace issues
- Added wrapping
- Fixed issues with mobile sizes
- Fixed sidebar sizing issues
- Fixed overflow issues

### CODE REVIEW

**Comment by j-tafoya** [comment]
closes #48

**Comment by j-tafoya** [comment]
@maheese I pushed up another commit to fix the need for horizontal scrolling on laptop size. Check it out here: https://test-power-profiler-drupal-upgrade.app.cloud.gov/

**Review by maheese — APPROVED** [review]
Looks good.

**Comment by j-tafoya** [comment]
Great! I'll merge now

**Pull request merged**
