### PR TITLE
Internationalization (i18n) feature

### LINKED ISSUE #12: Consolidate Spanish/English Versions
- [x] Get info on Spanish version protocol
- [ ] divy up app components to add translations
- [ ] determine how to handle dynamic components

### PR DESCRIPTION
**Pull request by j-tafoya**
- Added vue-i18n package to support multilingual single web app
- Added translations for all pages and components of the app
- Added translations for all dynamic content including d3 charts and maps
- Fixed any layout issues caused by the increase in text length from Spanish translations
- Fixed any minor bugs noticed along the way

See the TESTING.md file for guidance in testing while reviewing and please add to the doc as you see fit

Please see this version of the app hosted in cloud.gov here for review: https://test-power-profiler-i18n.app.cloud.gov/

closes #12 finally!

### CODE REVIEW

**Comment by ibarra-michelle** [comment]
Thx @j-tafoya ! There are two issues I have identified: 
- [ ] 1. Missing Fuel Mix and Emissions Rate text, see here:
image

- [ ] 2. Consistency issues - in the Fuel Mix section, the Fuel legend between English and Spanish are not the same (e.g., see coal and carbón) , see here:
image

**Comment by j-tafoya** [comment]
> Thx @j-tafoya ! There are two issues I have identified:
> 
> *  2. Consistency issues - in the Fuel Mix section, the Fuel legend between English and Spanish are not the same (e.g., see coal and carbón) , see here:
>   image

Thank you for reviewing! Is this comparing current in production to this branch? If so, this branch also has all the changes in master, including the color updates we did awhile back.

**Comment by ibarra-michelle** [comment]
> Thank you for reviewing! Is this comparing current in production to this branch? If so, this branch also has all the changes in master, including the color updates we did awhile back.

Good catch @j-tafoya - I was comparing the English colors that are in prod, not the t-power-profiler-i18n.app.cloud.gov English version. Disregard.

**Comment by maheese** [comment]
@j-tafoya everything looks good to me.  Great work!  Regarding @ibarra-michelle  comment about the Fuel Mix and Emission Rate text, it looks like it's there but just layed out differently.  I'm fine to merge this and fix the layout in another issue.  Your call.

**Review by maheese — APPROVED** [review]

**Comment by j-tafoya** [comment]
> @j-tafoya everything looks good to me. Great work! Regarding @ibarra-michelle comment about the Fuel Mix and Emission Rate text, it looks like it's there but just layed out differently. I'm fine to merge this and fix the layout in another issue. Your call.

I'm fine with that. That space is from the d3 stuff to make the charts align vertically, but when the screen is narrow and the charts are stacked, the space doesn't make sense anymore.

**Pull request merged**
