### PR TITLE
Add code.json file info

### PR DESCRIPTION
**Pull request by ibarra-michelle**
Currently, Power Profiler has no code.json file. This PR adds the code.json file info to Power Profiler's repo.

### CODE REVIEW

**Review by j-tafoya — APPROVED** [review]
Looks good to me. What do we have to add for licenses?

**Comment by ibarra-michelle** [comment]
> Looks good to me. What do we have to add for licenses?

@j-tafoya We should have a quick group chat to determine what license we should add - license pending ⏳

**Comment by ibarra-michelle** [comment]
@j-tafoya I added the MIT license and updated the code.json file to reflect the update.

**Comment by j-tafoya** [comment]
> @j-tafoya I added the MIT license and updated the code.json file to reflect the update.

Awesome! I think we can merge this at any time.

**Comment by ibarra-michelle** [comment]
> > @j-tafoya I added the MIT license and updated the code.json file to reflect the update.
> 
> Awesome! I think we can merge this at any time.

Great, thanks @j-tafoya . @maheese let me know if you approve and/or are OK to merge.

**Review by maheese — APPROVED** [review]
Looks good to me too.

**Pull request merged**
